[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
coin_toss_contract = "DgQs1qXHvkbBKJwgVP9DcS4EzN48beF9AEw5UpiCBSS3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/icarus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
